### ISSUE TITLE
Project using CsWin32 doesn't compile using msbuild because System.Memory is missing

### ISSUE THREAD

**Issue by SimonWeinbergerEnscape** [microsoft/CsWin32#875]
## Actual behavior

I'm trying to use CsWin32 source generators in our projects. It works when compiling in VisualStudio and works on our CI running "dotnet build", but doesn't run on our CI running "msbuild".

> ##[warning]CSC(0,0): Warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

## Expected behavior

Compiling with "msbuild" does work.

## Repro steps

1. Create a sln with a csproj which references CsWin32.
2. Build using MSBuild

I'm using Azure DevOps Server 2020 Update 1.1 with this step in a yaml pipeline, not sure what exactly happens in the background.
```yaml
  - task: VSBuild-sxs@1
    inputs:
      solution: MySolution.sln
      maximumCpuCount: true
      vsVersion: 17.0
      platform: Any CPU
      configuration: Debug
      msbuildArchitecture: x64
```
However, the build log indicates it's "msbuild MySolution.sln" with a bunch of extra options in the end that are probably just relevant for the CI.

## My own analysis

It looks like this an a general shortcoming of source generators, which must provide all their transitive dependencies. I have found this similar issue: https://github.com/dotnet/roslyn/issues/52017

Probably the CsWin32 nuget package needs to have all it's transitive dependencies in the analyzers/cs folder.

Maybe this is a duplicate of #560, but I'm not entirely sure.

### Context

- CsWin32 version: 0.2.188-beta
- Target Frameworks: net452;netcoreapp3.1;net6.0
- `LangVersion`: 9.0
